### ISSUE TITLE
does not launch on linux

### ISSUE THREAD

**Issue by absolutevm** [sylviiu/ezytdl#36] opened 2023-07-31 03:47 UTC
os: debian 12

when running the appimage from the system monitor it can be observed that the application starts and after 5-10 seconds crashes.
at some point i got an error about a stack trace though i wasn't able to get what it specifically was.

**Comment by sylviiu** [comment] 2023-07-31 13:20
can you launch it from the terminal and see the error it provides there? all stack traces should be logged there

**Comment by absolutevm** [comment] 2023-07-31 18:13
not sure how to run the appimage from terminal but from source (2.5.0-dev1) i have this log [error_ezytdl.txt](https://github.com/sylviiu/ezytdl/files/12217978/error_ezytdl.txt)

**Comment by sylviiu** [comment] 2023-07-31 18:43
this issue was caused by `ldconfig` not being found in the system -- i wasn't actually aware that it was not pre-installed on every linux distro (though i should've probably taken it into account)

this should be fixed by next nightly build (or you should be able to work-around this issue by installing `ldconfig` on your system)

if either work, please do let me know!

**Comment by absolutevm** [comment] 2023-07-31 18:55
yeah from what i can see ldconfig is not in my repos (or installed), so i'll just wait for the next nightly build and let you know how it goes

**Comment by sylviiu** [comment] 2023-07-31 21:02
doing a quick search for it, [it might be in the `libc-bin` package?](https://packages.debian.org/cgi-bin/search_contents.pl?word=ldconfig&searchmode=searchfiles&case=insensitive&version=stable&arch=i386)

try installing that and trying again -- if that doesn't work, i'll go ahead and build a new nightly for you before schedule

**Comment by absolutevm** [comment] 2023-07-31 21:28
unfortunately it's already installed at the newest version
![Screenshot from 2023-07-31 14-27-55](https://github.com/sylviiu/ezytdl/assets/113253898/5a4cc81f-4a9a-4bf9-aa2d-19c283618988)

**Comment by sylviiu** [comment] 2023-08-01 00:09
i gotcha. i've started the nightly build and it should be released in around ~10min from now

**Comment by absolutevm** [comment] 2023-08-01 00:34
new error
![image](https://github.com/sylviiu/ezytdl/assets/113253898/b1403854-606c-49d5-9eb7-37ac96b0c24c)

**Comment by absolutevm** [comment] 2023-08-01 00:37
i installed libvips and i think it's working now
![image](https://github.com/sylviiu/ezytdl/assets/113253898/38f4f9f9-0af7-44d4-abd4-1d9459b8bccb)

**Comment by sylviiu** [comment] 2023-08-01 02:58
i can definitely reproduce the 10-15 second start time, but so far as i know that's outside of my control. this is due to the compression used in appimage files; there isn't much i can do to fix that (i think??) :(

if you download and run the binary in the `tar.gz` download, it starts much quicker (but this will not work with auto updating, unfortunately)

otherwise, now that it's working, i can go ahead and close the issue :D

**Closed by sylviiu** 2023-08-01 02:58 UTC

**Comment by sylviiu** [comment] 2023-08-05 23:47
slow appimage speed has been fixed! (2185f11)

appimages used to build with maximum compression, which slowed them down LOTS (which previously I think didn't have issues??) -- they now build with the default compression, making them run much faster.

next dev build should let you use appimage again (which allows in-place auto updating)
