### ISSUE TITLE
error

### ISSUE THREAD

**Issue by deejaysyky** [sylviiu/ezytdl#140] opened 2024-01-21 14:41 UTC
### Title: 
Internal error occurred!

### Content: 
{}

SyntaxError: Bad escaped character in JSON at position 21393 (line 1 column 21394)
    at JSON.parse (<anonymous>)
    at C:\Users\pc\AppData\Local\Programs\ezytdl\resources\app.asar\util\currentVersion\pybridge.js:48:40
    at ChildProcess.exithandler (node:child_process:422:7)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.onexit (node:internal/child_process:302:5)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\pc\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:24:34)
- at module.exports (C:\Users\pc\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\pc\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:22:125)
- at process.emit (node:events:514:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment] 2024-03-04 23:04
duplicate of #121

**Closed by sylviiu** 2024-03-04 23:04 UTC
