### ISSUE TITLE
unable to find my model of MacBook Pro 

### ISSUE THREAD

**Issue by gahhhbriel** [sylviiu/ezytdl#105] opened 2023-11-23 21:42 UTC
### Title: 
Failed to determine hardware acceleration capabilities

### Content: 
Could not get video codec of "/var/folders/zx/62hxqx195tn__wvjysh8ggg40000gn/T/TRdCwRgisZMWMvxDaXbdZgnf-sample.mp4"

### Stack: 
```js
- at module.exports (/Applications/ezytdl.app/Contents/Resources/app.asar/core/sendNotification.js:9:30)
- at /Applications/ezytdl.app/Contents/Resources/app.asar/core/configActions.js:71:25
- at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment] 2023-12-04 00:29
Duplicate of #112; solution is [here](https://github.com/sylviiu/ezytdl/issues/112#issuecomment-1837659901)

**Closed by sylviiu** 2023-12-04 00:29 UTC
