### ISSUE TITLE
Internal error occurred! after running npm start or ezytdl.exe

### ISSUE THREAD

**Issue by Nameniok** [sylviiu/ezytdl#126] opened 2023-12-19 22:56 UTC
### Title: 
Internal error occurred!

### Content: 
{}

SyntaxError: Bad escaped character in JSON at position 21581 (line 1 column 21582)
    at JSON.parse (<anonymous>)
    at E:\Robienie Stron html css\ezytdl-main\dist\win-unpacked\resources\app.asar\util\currentVersion\pybridge.js:48:40
    at ChildProcess.exithandler (node:child_process:422:7)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.onexit (node:internal/child_process:302:5)

(no stack)

### Stack: 
```js
- at module.exports (E:\Robienie Stron html css\ezytdl-main\dist\win-unpacked\resources\app.asar\core\sendNotification.js:24:34)
- at module.exports (E:\Robienie Stron html css\ezytdl-main\dist\win-unpacked\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (E:\Robienie Stron html css\ezytdl-main\dist\win-unpacked\resources\app.asar\index.js:22:125)
- at process.emit (node:events:514:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
After running (npm start or .exe and settings) it's showing up.

**Comment by sylviiu** [comment] 2023-12-20 04:04
Duplicate of #121

**Closed by sylviiu** 2023-12-20 04:04 UTC
